# 数据库配置
DatabaseConfig:
  # Mysql配置
  MysqlConfig:
    host: 127.0.0.1  # 主机
    port: 3306  # 端口
    database_name: aamazon_spider  # 数据库名称
    username: root  # 用户名
    password: root  # 密码

  # Sqlalchemy配置
  SqlalchemyConfig:
    on_echo: false  # 是否开启查询日志

# 爬虫配置
SpiderConfig:
  # 关键词列表
  keywords:
    - 玩具
    - 电脑
    - 手机
  # 爬取数量（条）
  spider_size: 1000
  # 爬虫线程数，网速快可以设置多一点
  spider_worker: 10
  # 爬取URL模板
  search_url_template: https://www.amazon.com/s?k={}
  # 主页URL
  home_url: https://www.amazon.com
  # 是否开启代理
  proxies: true
  # 代理URL
  proxies_url: http://127.0.0.1:8889

